/'
simple-kubernetes-test-environment

Copyright (c) 2018 VMware, Inc. All Rights Reserved.

This product is licensed to you under the Apache 2.0 license (the "License").
You may not use this product except in compliance with the Apache 2.0 License.

This product may include a number of subcomponents with separate copyright
notices and license terms. Your use of these subcomponents is subject to the
terms and conditions of the subcomponent's license, as noted in the LICENSE
file.
'/

@startuml node-components
rectangle "Control plane node(s)\n" {
  agent "coredns"
  database "etcd"
  agent "nginx"
  agent "kube-apiserver" as kube_apiserver
  agent "kube-controller-manager" as kube_controller_manager
  agent "kube-scheduler" as kube_scheduler

  nginx --> kube_apiserver
  nginx -[hidden]-> kube_controller_manager
  nginx -[hidden]-> kube_scheduler
  coredns -right-> etcd
  kube_apiserver -down-> etcd
  kube_controller_manager -right-> kube_apiserver
  kube_apiserver -down-> kube_scheduler
}

rectangle "Worker node(s)\n" {
  agent "kubelet"
  agent "kube-proxy" as kube_proxy
  agent "containerd" as cri
  agent "iptables"
  component "runc"
  component "runsc"
  component "cni"

  kube_scheduler -right-> kubelet
  kubelet -[hidden]right-> kube_proxy
  kubelet -right-> cri
  cri <-up-> runc
  cri <-up-> runsc
  cri <-up-> cni
  iptables -[hidden]right-> cni
  iptables <-down- kube_proxy
}

@enduml